"""
Embed snake_ai.onnx into model_data.js as base64.

Run from inside snake/ (the folder containing snake_ai.onnx):

    python embed_model.py

game.js reads the global SNAKE_MODEL_B64 and decodes it straight into
ort.InferenceSession.create(). This exists because onnxruntime-web loads a
model path via fetch(), and browsers block fetch() of local files under
file:// — every file is its own opaque origin. Embedding sidesteps that, so
game.html works from a double-click with no local server.

Same pattern as tetris/training/embed_model.py; only the constant name
differs, since both models are loaded on different pages.

Re-run this after every export.py.
"""

import base64
import os

SRC = "snake_ai.onnx"
OUT = "model_data.js"
VAR = "SNAKE_MODEL_B64"

if not os.path.exists(SRC):
    raise SystemExit(
        f"Could not find {SRC} in this folder.\n"
        "Run training/export.py first, then copy snake_ai.onnx up into snake/."
    )

with open(SRC, "rb") as f:
    raw = f.read()

b64 = base64.b64encode(raw).decode("ascii")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by embed_model.py - do not edit by hand.\n")
    f.write("// snake_ai.onnx as base64, so it loads without fetch() under file://.\n")
    f.write(f'const {VAR} = "{b64}";\n')

print(
    f"Wrote {OUT} ({os.path.getsize(OUT) / (1024 * 1024):.2f} MB "
    f"from a {len(raw) / (1024 * 1024):.2f} MB model)."
)
