"""
Embed the game's PNG assets into image_data.js as base64 data URIs.

Why this exists — same root cause as embed_model.py in tetris/:

p5's loadImage() sets crossOrigin="Anonymous" on every URL that is not
already a data: URI. Opened over file://, the page's origin is opaque, so
that CORS request is rejected and the image silently never loads. The
sprites still exist and the physics still runs, so the game *appears* to
work — fruit merges, the score climbs — but nothing is drawn on the canvas.

Data URIs are the one path p5 skips the crossOrigin flag for, so embedding
sidesteps the restriction entirely and the game runs from a double-clicked
file with no local server.

Run this whenever the contents of assets/ change:

    python embed_assets.py        # → image_data.js
"""

import base64
import pathlib

ASSET_DIR = pathlib.Path(__file__).parent / "assets"
OUT_FILE = pathlib.Path(__file__).parent / "image_data.js"

MIME = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".gif": "image/gif"}


def main():
    if not ASSET_DIR.is_dir():
        raise SystemExit(f"No assets directory at {ASSET_DIR}")

    files = sorted(p for p in ASSET_DIR.iterdir() if p.suffix.lower() in MIME)
    if not files:
        raise SystemExit(f"No images found in {ASSET_DIR}")

    lines = [
        "// Generated by embed_assets.py — do not edit by hand.",
        "// Keys are the same relative paths the game would otherwise request,",
        "// so game.js can fall back to plain paths when this file is absent.",
        "const WATERMELON_IMAGES = {",
    ]

    total = 0
    for path in files:
        raw = path.read_bytes()
        total += len(raw)
        b64 = base64.b64encode(raw).decode("ascii")
        key = f"assets/{path.name}"
        lines.append(f'  "{key}": "data:{MIME[path.suffix.lower()]};base64,{b64}",')

    lines.append("};")
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    out_kb = OUT_FILE.stat().st_size / 1024
    print(f"Embedded {len(files)} images ({total / 1024:.0f} KB raw) -> {OUT_FILE.name} ({out_kb:.0f} KB)")


if __name__ == "__main__":
    main()
