"""
One-time conversion script.

Run this from inside your tetris/ folder (the one containing tetris_ai.onnx):

    python3 embed_model.py

It reads tetris_ai.onnx and writes model_data.js, which embeds the model as a
base64 string. This lets game.js load the model from memory instead of
fetch()-ing the file — which is what lets you open game.html directly by
double-clicking it (file://) without needing to run a local server.
"""

import base64
import os

SRC = "tetris_ai.onnx"
OUT = "model_data.js"

if not os.path.exists(SRC):
    raise SystemExit(f"Could not find {SRC} in this folder. Run this script from inside tetris/.")

with open(SRC, "rb") as f:
    raw = f.read()

b64 = base64.b64encode(raw).decode("ascii")

with open(OUT, "w") as f:
    f.write("// Auto-generated by embed_model.py — do not edit by hand.\n")
    f.write("// Contains tetris_ai.onnx encoded as base64 so it can be loaded\n")
    f.write("// without fetch() (works when opening game.html directly).\n")
    f.write(f'const TETRIS_MODEL_B64 = "{b64}";\n')

size_mb = len(raw) / (1024 * 1024)
out_mb = os.path.getsize(OUT) / (1024 * 1024)
print(f"Wrote {OUT} ({out_mb:.2f} MB from {size_mb:.2f} MB model).")
print("Re-run this script any time you export a new tetris_ai.onnx.")
