/* GENERATED by tools/build_checkpoints.py — do not edit by hand.
 *
 * The checkpoint ladders the in-game switcher offers. Each rung's score
 * is MEASURED by playing the exact .onnx the browser downloads, at
 * argmax, over `episodes` fixed-seed games — not copied from the
 * archive filenames. `steps` is num_timesteps out of the checkpoint
 * itself: how much training the run that produced it had done.
 *
 * stepsMeaning is 'lineage' when a game's step counts form one
 * continuous run and can be compared, and 'run' when they cannot —
 * see the long note in the builder. The switcher only shows steps for
 * a 'lineage' ladder.
 *
 * Rungs are ordered weakest to strongest by measured score, which is
 * not always the order they were trained in — that is the point of
 * measuring rather than assuming.
 */
const CHECKPOINTS = {
  "snake": {
    "stepsMeaning": "run",
    "rungs": [
      {
        "id": "s1",
        "file": "checkpoints/s1.onnx",
        "steps": 30015488,
        "bytes": 35660336,
        "shipped": false,
        "score": 71.33,
        "median": 73.0,
        "min": 41.0,
        "max": 103.0,
        "episodes": 30,
        "capped": 0
      },
      {
        "id": "s2",
        "file": "checkpoints/s2.onnx",
        "steps": 40009728,
        "bytes": 35660336,
        "shipped": false,
        "score": 105.7,
        "median": 108.0,
        "min": 72.0,
        "max": 148.0,
        "episodes": 30,
        "capped": 0
      },
      {
        "id": "s3",
        "file": "checkpoints/s3.onnx",
        "steps": 6029312,
        "bytes": 35660336,
        "shipped": false,
        "score": 129.17,
        "median": 140.0,
        "min": 78.0,
        "max": 177.0,
        "episodes": 30,
        "capped": 0
      },
      {
        "id": "s4",
        "file": "snake_ai.onnx",
        "steps": 55000032,
        "bytes": 35660336,
        "shipped": true,
        "score": 149.47,
        "median": 157.0,
        "min": 102.0,
        "max": 174.0,
        "episodes": 30,
        "capped": 0
      }
    ]
  },
  "watermelon": {
    "stepsMeaning": "run",
    "rungs": [
      {
        "id": "w1",
        "file": "watermelon_ai.onnx",
        "steps": 0,
        "bytes": 23773797,
        "shipped": true,
        "score": 4505.5,
        "median": 4310.0,
        "min": 2927.0,
        "max": 8591.0,
        "episodes": 30,
        "capped": 0
      }
    ]
  },
  "tetris": {
    "stepsMeaning": "lineage",
    "rungs": [
      {
        "id": "t1",
        "file": "checkpoints/t1.onnx",
        "steps": 70841232,
        "bytes": 7360522,
        "shipped": false,
        "score": 746.5,
        "median": 695.0,
        "min": 240.0,
        "max": 2105.0,
        "episodes": 20,
        "capped": 0
      },
      {
        "id": "t2",
        "file": "checkpoints/t2.onnx",
        "steps": 261018352,
        "bytes": 7360522,
        "shipped": false,
        "score": 1188.0,
        "median": 1295.0,
        "min": 170.0,
        "max": 2560.0,
        "episodes": 20,
        "capped": 0
      },
      {
        "id": "t3",
        "file": "tetris_ai.onnx",
        "steps": 1000012896,
        "bytes": 7360599,
        "shipped": true,
        "score": 106774.5,
        "median": 65725.0,
        "min": 6295.0,
        "max": 530715.0,
        "episodes": 20,
        "capped": 0
      }
    ]
  }
};
if (typeof window !== 'undefined') window.CHECKPOINTS = CHECKPOINTS;
